### ISSUE TITLE
Can't use MOD-UI; dependency job fails

### ISSUE THREAD

**Issue by Robert-K** [zynthian/zynthian-issue-tracking#485]
**Describe the bug**
Adding a MOD-UI layer does not work. Selecting "MOD-UI - Plugin Host" results in the Zynthian logo moving for a sec and stopping.
The console outputs:
```
Jul 27 01:58:48 zynthian startx[12952]: A dependency job for mod-ui.service failed. See 'journalctl -xe' for details.
Jul 27 01:58:48 zynthian startx[12952]: ERROR:zynthian_gui.zyncoder_read: Command 'systemctl start mod-ui' returned non-zero exit status 1.
Jul 27 01:58:48 zynthian startx[12952]: Traceback (most recent call last):
Jul 27 01:58:48 zynthian startx[12952]: File "./zynthian_gui.py", line 1252, in zyncoder_read
Jul 27 01:58:48 zynthian startx[12952]: self.zynswitch_defered_exec()
Jul 27 01:58:48 zynthian startx[12952]: File "./zynthian_gui.py", line 1201, in zynswitch_defered_exec
Jul 27 01:58:48 zynthian startx[12952]: self.zynswitch_short(event[1])
Jul 27 01:58:48 zynthian startx[12952]: File "./zynthian_gui.py", line 1147, in zynswitch_short
Jul 27 01:58:48 zynthian startx[12952]: self.screens[self.modal_screen].switch_select('S')
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 251, in switch_select
Jul 27 01:58:48 zynthian startx[12952]: self.click_listbox(None, t)
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 247, in click_listbox
Jul 27 01:58:48 zynthian startx[12952]: self.select_action(self.index, t)
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py", line 169, in select_action
Jul 27 01:58:48 zynthian startx[12952]: self.zyngui.screens['layer'].add_layer_engine(self.list_data[i][0], self.midi_chan)
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 281, in add_layer_engine
Jul 27 01:58:48 zynthian startx[12952]: self.add_layer_midich(None)
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 303, in add_layer_midich
Jul 27 01:58:48 zynthian startx[12952]: zyngine = self.zyngui.screens['engine'].start_engine(self.add_layer_eng)
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py", line 180, in start_engine
Jul 27 01:58:48 zynthian startx[12952]: self.zyngines[eng]=zynthian_engine_class(self.zyngui)
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngine/zynthian_engine_modui.py", line 85, in __init__
Jul 27 01:58:48 zynthian startx[12952]: self.start()
Jul 27 01:58:48 zynthian startx[12952]: File "/home/pi/zynthian-ui/zyngine/zynthian_engine_modui.py", line 101, in start
Jul 27 01:58:48 zynthian startx[12952]: check_output(("systemctl start mod-ui"),shell=True)
Jul 27 01:58:48 zynthian startx[12952]: File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
Jul 27 01:58:48 zynthian startx[12952]: **kwargs).stdout
Jul 27 01:58:48 zynthian startx[12952]: File "/usr/lib/python3.7/subprocess.py", line 487, in run
Jul 27 01:58:48 zynthian startx[12952]: output=stdout, stderr=stderr)
Jul 27 01:58:48 zynthian startx[12952]: subprocess.CalledProcessError: Command 'systemctl start mod-ui' returned non-zero exit status 1.
```

And running `journalctx -xe` reveals:

```
Jul 27 01:43:46 zynthian systemd[1]: Starting MOD-HOST: LV2 plugin server...
-- Subject: A start job for unit mod-host.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mod-host.service has begun execution.
--
-- The job identifier is 1298.
Jul 27 01:43:46 zynthian jackd[472]: error: PROTOCOL_MAX_COMMANDS reached (reconfigure it)
Jul 27 01:43:46 zynthian jackd[472]: error: PROTOCOL_MAX_COMMANDS reached (reconfigure it)
Jul 27 01:43:46 zynthian jackd[472]: No jack_get_descriptor entry-point for mod-monitor
Jul 27 01:43:46 zynthian jack_load[8643]: mod-monitor is running.
Jul 27 01:43:46 zynthian jack_load[8643]: client name = mod-monitor
Jul 27 01:43:47 zynthian jackd[472]: No jack_get_descriptor entry-point for mod-host
Jul 27 01:43:47 zynthian jackd[472]: failed to open mod-monitor client
Jul 27 01:43:47 zynthian jack_load[8647]: could not load mod-host, intclient = 0 status = 0x 1
Jul 27 01:43:47 zynthian systemd[1]: mod-host.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit mod-host.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 2.
Jul 27 01:43:47 zynthian jack_unload[8650]: mod-monitor unloaded.
Jul 27 01:43:47 zynthian systemd[1]: mod-host.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit mod-host.service has entered the 'failed' state with result 'exit-code'.
Jul 27 01:43:47 zynthian systemd[1]: Failed to start MOD-HOST: LV2 plugin server.
-- Subject: A start job for unit mod-host.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mod-host.service has finished with a failure.
--
-- The job identifier is 1298 and the job result is failed.
Jul 27 01:43:47 zynthian systemd[1]: Dependency failed for MOD-UI.
-- Subject: A start job for unit mod-ui.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mod-ui.service has finished with a failure.
--
-- The job identifier is 1297 and the job result is dependency.
Jul 27 01:43:47 zynthian systemd[1]: mod-ui.service: Job mod-ui.service/start failed with result 'dependency'.
```

**To Reproduce**
1. Click NEW Special Layer
2. Click MOD-UI - Plugin Host
3. Suffer

**Expected behavior**
MOD-UI starts I guess. Never got to that point :|

**Setup:**
running unmodified stable OS, latest version:
zyncoder: stable (d852c8f)
zynthian-ui: stable (b2f6a7c)
zynthian-sys: stable (aefaf98)
zynthian-data: stable (f71259d)
zynthian-webconf: stable (153a020)

Pi4 with Waveshare 3.5A and Sabrent USB Audio Adapter

**Additional context**
This is the only real error I've encountered so far.
Love the project, keep up the great work ❤ thank you

**Comment by riban-bw** [comment]
mod-ui service is not starting because a dependancy, mod-host is failing to start. The attempt to start mod-host fails with message:
```
Failed to start MOD-HOST: LV2 plugin server.
```

Log also shows:
```
Starting MOD-HOST: LV2 plugin server...
No jack_get_descriptor entry-point for mod-monitor
loading 2 instances of monitor client is not allowed
could not load mod-monitor, intclient = 0 status = 0x 5
```
so there seems to be a second attempt to load mod-monitor jack client.

Loading mod-monitor creates a client with name `mod-monitor-01` so subsequent attempt to unload mod-monitor fails. I am not sure (yet) why mod-monitor client has -01 suffix added when there appears to be no existing mod-monitor loaded.

**Comment by riban-bw** [comment]
Getting PID of jackd with `ps ax|grep jack` then getting list of files open by jack, filtered by 'mod' with `lsof -P -T -p xxx|grep mod` (where xxx is PID of jackd) I observe that a clean Zynthian has one entry:
```
/usr/local/lib/jack/mod-host.so
```
i.e. jackd loads mod-host shared library even when not in use.

Loading mod-host with `jack_load mod-host` and running above command shows:
```
/usr/local/lib/jack/mod-host.so
/dev/shm/jack_sem.0_default_mod-monitor
/dev/shm/jack_sem.0_default_mod-host
/dev/shm/jack_sem.0_default_mod-host
/dev/shm/jack_sem.0_default_mod-monitor
```
i.e. mod-host and mod-monitor are loaded. Unloading and reloading mod-host fails, possibly due to it trying to load mod-monitor. The systemd start attempts to start mod-monitor which may fail because mod-monitor is already loaded by mod-host.

I am not sure what has changed or why - this was working last week!

**Comment by riban-bw** [comment]
Loading and unloading mod-monitor by itself works. Loading mod-host seems to also load mod-monitor but unloading mod-host does not unload mod-monitor. This leaves the system in an inconsistent state where it cannot load mod-host because mod-monitor is already loaded and it cannot unload mod-monitor because it doesn't know it is loaded! I wonder if this issue lies in a different version of jackd being use - possibly installed from Debian when using _testing_ branch then subsequently changing to _stable_ but with the new excecutables still loaded.

@Robert-K did you switch to _testing_ at any time?

**Comment by Robert-K** [comment]
@riban-bw I did! Intended to try zynmixer, but upon switching repo and updating, nothing really worked. So i returned to stable. I don't recall MOD-UI working before that but probably because I didn't even try.

**Comment by riban-bw** [comment]
Thanks Robert. @jofemodo it looks like we have a significant issue with the full update from Debian enabled in _Testing_ which we need to resolve as a matter of urgency. When this is resolved and _Testing_ is merged with _Stable_ we should see better handling of switching between the two but currently it seems that _Testing_ is broken and anyone switching from _Testing_ to _Stable_ will also be broken.

**Comment by jofemodo** [comment]
It should be solved on testing now. Please, update, test and confirm.
Thanks!

**Comment by jofemodo** [comment]
Please, confirm this is solved now!

Thanks!

**Comment by riban-bw** [comment]
I just tried this and found loading an existing board appeared to work but no audio was passing through the board. Removing the layer then attempting to add MOD-UI again resulted in failure - loading animation for a few seconds then stops without succeeding. Log extract:

```
Aug 05 14:05:55 zynthian1 startx[500]: A dependency job for mod-ui.service failed. See 'journalctl -xe' for details.
Aug 05 14:05:55 zynthian1 startx[500]: ERROR:zynthian_gui.zyncoder_read: Command 'systemctl start mod-ui' returned non-zero exit status 1.
Aug 05 14:05:55 zynthian1 startx[500]: Traceback (most recent call last):
Aug 05 14:05:55 zynthian1 startx[500]:   File "./zynthian_gui.py", line 1270, in zyncoder_read
Aug 05 14:05:55 zynthian1 startx[500]:     self.zynswitches()
Aug 05 14:05:55 zynthian1 startx[500]:   File "./zynthian_gui.py", line 977, in zynswitches
Aug 05 14:05:55 zynthian1 startx[500]:     self.zynswitch_short(i)
Aug 05 14:05:55 zynthian1 startx[500]:   File "./zynthian_gui.py", line 1164, in zynswitch_short
Aug 05 14:05:55 zynthian1 startx[500]:     self.screens[self.modal_screen].switch_select('S')
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 251, in switch_select
Aug 05 14:05:55 zynthian1 startx[500]:     self.click_listbox(None, t)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 247, in click_listbox
Aug 05 14:05:55 zynthian1 startx[500]:     self.select_action(self.index, t)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py", line 168, in select_action
Aug 05 14:05:55 zynthian1 startx[500]:     self.zyngui.screens['layer'].add_layer_engine(self.list_data[i][0], self.midi_chan)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 300, in add_layer_engine
Aug 05 14:05:55 zynthian1 startx[500]:     self.add_layer_midich(None)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 323, in add_layer_midich
Aug 05 14:05:55 zynthian1 startx[500]:     zyngine = self.zyngui.screens['engine'].start_engine(self.add_layer_eng)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py", line 179, in start_engine
Aug 05 14:05:55 zynthian1 startx[500]:     self.zyngines[eng]=zynthian_engine_class(self.zyngui)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngine/zynthian_engine_modui.py", line 86, in __init__
Aug 05 14:05:55 zynthian1 startx[500]:     self.start()
Aug 05 14:05:55 zynthian1 startx[500]:   File "/home/pi/zynthian-ui/zyngine/zynthian_engine_modui.py", line 102, in start
Aug 05 14:05:55 zynthian1 startx[500]:     check_output(("systemctl start mod-ui"),shell=True)
Aug 05 14:05:55 zynthian1 startx[500]:   File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
Aug 05 14:05:55 zynthian1 startx[500]:     **kwargs).stdout
Aug 05 14:05:55 zynthian1 startx[500]:   File "/usr/lib/python3.7/subprocess.py", line 487, in run
Aug 05 14:05:55 zynthian1 startx[500]:     output=stdout, stderr=stderr)
Aug 05 14:05:55 zynthian1 startx[500]: subprocess.CalledProcessError: Command 'systemctl start mod-ui' returned non-zero exit status 1.
```
So looks like issue persists.

**Comment by riban-bw** [comment]
It does seem to be the second time you load the MOD-UI engine fails.

**Comment by jofemodo** [comment]
It seems that mod-host auto-loads mod-monitor. That's OK and i removed the explicit loading of mod-monitor from the service file. But when mod-host is unloaded, mod-monitor remains active. Trying to unload mod-monitor doesn't work. Trying to load mod-host again fails ;-(

Ideas?

**Comment by riban-bw** [comment]
That is exactly what I discovered. I think there is a bug in an upstream project jack/mod-ui. I didn't investigate the mechanism that auto-loads mod-monitor but I think it is embedded within the mod-host code. I also saw duplicate instances of each. It is odd that jackd can report it has an internal client loaded but refuses to unload it.

**Comment by riban-bw** [comment]
A blunt tool may be to save last state snapshot then restart jack2 service when removing mod-ui layer. It used to cause problems to stop jack2 but I just tried it and things _seem_ to work okay. This is not a nice solution but better it looks ugly but works.

**Comment by jofemodo** [comment]
A different approach is keeping mod-host running once it's started for first time. mod-host itself it's not resource hungry. We could try and see.

**Comment by riban-bw** [comment]
Agreed! Either way there needs to be a check in the mod-ui engine for the existence of an instance of mod-ui. Leaving it running once started seems like a good starting point. It would require a removal of the layer and a reboot to stop it but that seems okay for a workaround. Do it!

**Comment by jofemodo** [comment]
Done! It works like a charm ;-)
No need to keep running mod-ui, only mod-host.

**Comment by riban-bw** [comment]
I'm not convinced. Although mod-ui will now start I cannot get any audio to flow through it!

**Comment by jofemodo** [comment]
It works perfectly for me. I'm using latest testing.

I tried using mod-ui as audio FX, routing other layer's audio thru mod-monitor. Also tried as a synth engine. It worked flawlessly for me. 

Regards,

**Comment by riban-bw** [comment]
Ah yes! It helps if I plug into the right input... Well done!

**Comment by Robert-K** [comment]
If I'm not mistaken it's still broken on the latest stable release.. right?
I wrote the image to a SD card, did not try testing, updated through the webconf and got the same error.
I'd tried the latest testing image as well, but with that one, the screen doesn't work and my zynthian doesn't even connect to the network on the second boot  :(

**Comment by riban-bw** [comment]
Stable update due soon (maybe within the week).

Did you remember to configure your custom configuration for screen, soundcard, etc. on the _Testing_ image?
